### ISSUE TITLE
dgbk-0011: create plex role

### ISSUE THREAD

**Issue by tojathedog** [tojathedog/dogbooks#14]
create role to setup plex if it dies

### to-do:
- [ ] installs plex-media-server package from.... plex
- [ ] enables plex-media-server service
- [ ] some config via template? (check plex site)
