### ISSUE TITLE
dgbk-0013: create pxe server role

### ISSUE THREAD

**Issue by tojathedog** [tojathedog/dogbooks#16]
## task:  create util server role

will have both pxe and ~personal repo for packages i don't want to lose~ (make repo role separate, pxe role is already quite a few tasks)

### deliverables:
this role should be able to:
- [ ] install pxe services
 - [ ] install packages
  - [ ] syslinux
  - [ ] tftpd
 - [ ] setup firewall stuff (only allow local lan network)
 - [ ] setup pxe config (template, obviously)
 - [ ] enable and start pxe services (tftpd)
 - [ ] setup pxe boot menu
  - [ ] setup from role vars file
 - [ ] download, extract, and setup iso files
  - [ ] also from role vars file for easy redeployment if i add a distro

**Comment by tojathedog** [comment]
### deliverables:
this role should be able to:
- install pxe services
-- install packages
--- syslinux
--- tftpd
-- setup firewall stuff (only allow local lan network)
-- setup pxe config (template, obviously)
-- enable and start pxe services (tftpd)
- setup pxe boot menu
-- setup from role vars file
- download, extract, and setup iso files
-- also from role vars file for easy redeployment if i add a distro
